version: "1.0"
project_name: "Python Text Extraction Libraries Benchmarks"
description: "Comprehensive benchmarking suite for Python text extraction frameworks"

# Kreuzberg Configuration Notes
kreuzberg_optimizations:
  default_configuration:
    description: "Kreuzberg defaults are optimized out-of-the-box for modern documents"
    settings:
      psm: "AUTO_ONLY"  # Fast without orientation detection overhead
      language_model_ngram_on: false  # Optimized for modern documents
      tessedit_enable_dict_correction: true  # Balanced accuracy
    use_cases:
      - "Modern PDFs and standard documents"
      - "Optimal speed and quality balance"
  
  accuracy_configuration:
    description: "Enhanced configuration for degraded or historical documents"
    settings:
      psm: "AUTO"  # Full analysis with orientation detection
      language_model_ngram_on: true  # Better for degraded text
      tessedit_enable_dict_correction: true  # Correct OCR errors
    use_cases:
      - "Scanned documents"
      - "Historical documents"
      - "Noisy/degraded images"

# Benchmark Configuration
benchmark_settings:
  iterations: 3  # Default number of iterations per document
  timeout: 300  # Seconds per extraction
  warmup_runs: 0  # No warmup for cold-start performance
  cache_clearing: true  # Clear Kreuzberg cache between runs

# Test Document Categories
document_categories:
  tiny: "< 100KB"
  small: "100KB - 1MB"
  medium: "1MB - 10MB"
  large: "10MB - 50MB"
  huge: "> 50MB"

# Performance Expectations
expected_performance:
  kreuzberg_tesseract:
    small_files: "12.8 files/sec"
    medium_files: "3.7 files/sec"
  kreuzberg_tesseract_default:
    note: "Similar speed but potentially better quality on degraded text"