[global]
remove_todos = false
remove_fixme = false
remove_docs = false
preserve_patterns = ["HACK", "WORKAROUND", "NOTE", "~keep"]
use_default_ignores = true
respect_gitignore = true
traverse_git_repos = false

[languages.javascript]
name = "JavaScript"
extensions = [".js", ".jsx", ".mjs", ".cjs"]
comment_nodes = ["comment"]
preserve_patterns = ["@ts-expect-error", "@ts-ignore", "webpack", "eslint-"]

[languages.python]
name = "Python"
extensions = [".py", ".pyw", ".pyi"]
comment_nodes = ["comment"]
preserve_patterns = ["mypy:", "type:", "noqa:", "pragma:", "pylint:", "~keep"]
remove_docs = false

[patterns."tests/**/*"]
remove_todos = true

[patterns."**/*.spec.*"]
remove_docs = true
remove_todos = true

[patterns."**/*.generated.*"]
remove_docs = true
remove_todos = true
preserve_patterns = []
